
// GALPONES

app-Router["1", "crearGalpon", "/dashboard/barn/crear", 1]

app-Router["2", "listarGalpones", "/dashboard/barn/listar", 1]


// LOTES DE AVES

app-Router["3", "crearLoteAves", "/dashboard/birdBatch/crear", 1]

app-Router["4", "listarLotesAves", "/dashboard/birdBatch/listar", 1]


// PESAJE

app-Router["5", "crearPesaje", "/dashboard/weighing/crear", 1]

app-Router["6", "listarPesajes", "/dashboard/weighing/listar", 1]


// MORTALIDAD

app-Router["7", "crearMortalidad", "/dashboard/mortality/crear", 1]

app-Router["8", "listarMortalidad", "/dashboard/mortality/listar", 1]


// ALIMENTACIÓN

app-Router["9", "crearAlimentacion", "/dashboard/feeding/crear", 1]

app-Router["10", "listarAlimentaciones", "/dashboard/feeding/listar", 1]


// PRODUCCIÓN DE HUEVOS

app-Router["11", "crearProduccionHuevos", "/dashboard/eggProduction/crear", 1]

app-Router["12", "listarProduccionesHuevos", "/dashboard/eggProduction/listar", 1]


// SALUD

app-Router["13", "crearSalud", "/dashboard/health/crear", 1]

app-Router["14", "listarSalud", "/dashboard/health/listar", 1]


// CUARENTENA

app-Router["15", "crearCuarentena", "/dashboard/quarantine/crear", 1]

app-Router["16", "listarCuarentenas", "/dashboard/quarantine/listar", 1]


// VISITAS

app-Router["17", "crearVisita", "/dashboard/visit/crear", 1]

app-Router["18", "listarVisitas", "/dashboard/visit/listar", 1]


// INSUMOS

app-Router["19", "crearInsumo", "/dashboard/supply/crear", 1]

app-Router["20", "listarInsumos", "/dashboard/supply/listar", 1]


// RESPONSABLES

app-Router["21", "crearResponsable", "/dashboard/responsible/crear", 1]

app-Router["22", "listarResponsables", "/dashboard/responsible/listar", 1]


// USUARIOS

app-Router["23", "crearUsuario", "/dashboard/user/crear", 1]

app-Router["24", "listarUsuarios", "/dashboard/user/listar", 1]