export const DEFAULT_ROLES = [
  { slug: "superadmin", name_roll: "Super Administrador"},
  { slug: "admin", name_roll: "Administrador"},
  { slug: "gestor", name_roll: "Gestor"},
  { slug: "Pasante", name_roll: "Pasante"},
  { slug: "Instructor", name_roll: "Instructor"},
]

export const DEFAULT_APP_ROUTES = [
  {
    name_route: "Dashboard",
    route: "/dashboard",
    active: true,
    icono: "fa-solid fa-house"
  }
]

export const DEFAULT_ROLL_APP_ROUTES = [

]